# Generated by Django 5.1.7 on 2026-09-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGEMENT', 'Management'), ('TEAM_LEADER', 'Team Leader')], max_length=20),
        ),
    ]
